use_frameworks!

target 'VVFoundation_Example' do
  pod 'VVFoundation', :path => '../'

  target 'VVFoundation_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
